name: prime_counter
description: "A new Flutter project."

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  dartz: ^0.10.1
  shared_preferences: ^2.5.2
  equatable: ^2.0.7
  intl: ^0.20.2
  get_it: ^8.0.3
  mockito: ^5.4.5
  bloc_test: ^10.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/core/gen
  line_length: 80



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: RR
      fonts:
        - asset: lib/core/fonts/Roboto_Regular.ttf
